
# models and weights here: https://pytorch.org/vision/stable/models.html

model:
  num_classes: 3
  name: resnet50
  weights: ResNet50_Weights.IMAGENET1K_V2


dataset:
  train: ./dataset/oral/train.json
  test: ./dataset/oral/test.json
  resize: 224


train:
  save_path: ""
  seed: -1
  batch_size: 32
  lr: 0.001
  accelerator: "gpu"
  devices: 1
  max_epochs: 10

log:  
  wandb: False
  tensorboard: False
