
# ResNet50_Weights.IMAGENET1K_V2
# GoogLeNet_Weights.IMAGENET1K_V1
# ViT_B_16_Weights.IMAGENET1K_SWAG_LINEAR_V1
# EfficientNet_B1_Weights.IMAGENET1K_V2
# DenseNet161_Weights.IMAGENET1K_V1
# Swin_T_Weights.IMAGENET1K_V1
# VGG13_BN_Weights.IMAGENET1K_V1
# RegNet_Y_1_6GF_Weights.IMAGENET1K_V2
# MobileNet_V3_Large_Weights.IMAGENET1K_V2
# MaxVit_T_Weights.IMAGENET1K_V1
# ConvNeXt_Tiny_Weights.IMAGENET1K_V1

model:
  num_classes: 3
  name: mobilenet_v3_large
  weights: MobileNet_V3_Large_Weights.IMAGENET1K_V2
  features_size: 512

dataset:
  train: ./data/train.json
  val: ./data/val.json
  test: ./data/test.json
  resize: 224
  original: ./data/dataset.json

train:
  save_path: "./models/"
  seed: -1
  batch_size: 64
  lr: 0.000005

  accelerator: "gpu"
  devices: 1
  max_epochs: 600
  frozen_layers: 0

log:  
  path: "./logs/new/"
  dir: "oral"
  wandb: False
  tensorboard: True
